

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_empty_default_hostname():
    return False


def instance_min_collection_interval():
    return 15


def instance_send_distribution_buckets():
    return False


def instance_send_distribution_counts_as_monotonic():
    return False


def instance_send_distribution_sums_as_monotonic():
    return False


def instance_send_histograms_buckets():
    return False