from datadog_checks.dev.jmx import JVM_E2E_METRICS_NEW

METRICS = [
    'flume.channel.capacity',
    'flume.channel.fill_percentage',
    'flume.channel.size',
    'flume.channel.event_put_attempt_count',
    'flume.channel.event_put_success_count',
    'flume.channel.event_take_attempt_count',
    'flume.channel.event_take_success_count',
    'flume.channel.kafka_commit_timer',
    'flume.channel.kafka_event_get_timer',
    'flume.channel.kafka_event_send_timer',
    'flume.channel.rollbackcount',
    'flume.sink.connection_created_count',
    'flume.sink.connection_closed_count',
    'flume.sink.connection_failed_count',
    'flume.sink.batch_empty_count',
    'flume.sink.batch_underflow_count',
    'flume.sink.batch_complete_count',
    'flume.sink.event_drain_attempt_count',
    'flume.sink.event_drain_success_count',
    'flume.sink.event_write_fail',
    'flume.sink.channel_read_fail',
    'flume.sink.kafka_event_sent_timer',
    'flume.sink.rollbackcount',
    'flume.source.event_read_fail',
    'flume.source.event_received_count',
    'flume.source.event_accepted_count',
    'flume.source.append_received_count',
    'flume.source.append_accepted_count',
    'flume.source.append_batch_received_count',
    'flume.source.append_batch_accepted_count',
    'flume.source.open_connection_count',
    'flume.source.channel_write_fail',
    'flume.source.generic_processing_fail',
    'flume.source.kafka_commit_timer',
    'flume.source.kafka_empty_count',
    'flume.source.kafka_event_get_timer',
] + JVM_E2E_METRICS_NEW
