FROM foundationdb/foundationdb:6.3.13
WORKDIR /var/fdb/tmp
COPY fdb.bash /var/fdb/scripts/fdb-new.bash
COPY cert.crt /var/fdb/cert.crt
COPY fdb.pem /var/fdb/fdb.pem
COPY private.key /var/fdb/private.key
ENTRYPOINT ["/bin/sh", "-c", "/var/fdb/scripts/fdb-new.bash"]