EXPECTED_METRICS = {
    "php_opcache.opcache_enabled": 1,
    "php_opcache.cache_full": 0,
    "php_opcache.restart_pending": 0,
    "php_opcache.restart_in_progress": 0,
    "php_opcache.memory_usage.used_memory": 0,
    "php_opcache.memory_usage.free_memory": 1,
    "php_opcache.memory_usage.wasted_memory": 0,
    "php_opcache.memory_usage.current_wasted_percentage": 0,
    "php_opcache.interned_strings_usage.buffer_size": 1,
    "php_opcache.interned_strings_usage.used_memory": 1,
    "php_opcache.interned_strings_usage.free_memory": 0,
    "php_opcache.interned_strings_usage.number_of_strings": 0,
    "php_opcache.opcache_statistics.num_cached_scripts": 1,
    "php_opcache.opcache_statistics.num_cached_keys": 1,
    "php_opcache.opcache_statistics.max_cached_keys": 1,
    "php_opcache.opcache_statistics.hits": 0,
    "php_opcache.opcache_statistics.start_time": 1,
    "php_opcache.opcache_statistics.last_restart_time": 0,
    "php_opcache.opcache_statistics.oom_restarts": 0,
    "php_opcache.opcache_statistics.hash_restarts": 0,
    "php_opcache.opcache_statistics.manual_restarts": 0,
    "php_opcache.opcache_statistics.misses": 1,
    "php_opcache.opcache_statistics.blacklist_misses": 0,
    "php_opcache.opcache_statistics.blacklist_miss_ratio": 0,
    "php_opcache.opcache_statistics.opcache_hit_rate": 0,
}
