METRIC_MAP = {
    "typha_cache_size": "cache.size",
    "typha_snapshots_generated": "snapshots.generated",
    "typha_snapshots_reused": "snapshots.reused",
    "typha_snapshot_raw_bytes": "snapshot.raw.bytes",
    "typha_snapshot_compressed_bytes": "snapshots.compressed.bytes",
    "typha_breadcrumb_block": "breadcrumb.block",
    "typha_breadcrumb_non_block": "breadcrumb.non.block",
    "typha_breadcrumb_seq_number": "breadcrumb.seq.number",
    "typha_connections_accepted": "connections.accepted",
    "typha_connections_active": "connections.active",
    "typha_connections_streaming": "connections.streaming",
    "typha_connections_dropped": "connections.dropped",
    "typha_log_errors": "log.errors",
    "typha_logs_dropped": "logs.dropped",
    "typha_updates_skipped": "updates.skipped",
    "typha_updates_total": "updates.total",
}
