# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_cumulative():
    return True


def instance_disable_generic_tags():
    return False


def instance_duration():
    return 60


def instance_empty_default_hostname():
    return False


def instance_env():
    return 'prod'


def instance_min_collection_interval():
    return 1


def instance_tls_validate_hostname():
    return True


def instance_tls_verify():
    return True
