# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_tags(field, value):
    return get_default_field_value(field, value)


def instance_cumulative(field, value):
    return True


def instance_duration(field, value):
    return 15


def instance_empty_default_hostname(field, value):
    return False


def instance_env(field, value):
    return 'prod'


def instance_min_collection_interval(field, value):
    return 60


def instance_profiles(field, value):
    return get_default_field_value(field, value)


def instance_tags(field, value):
    return get_default_field_value(field, value)
