counter = {
    'ravendb_network_total_requests': 'network.total.requests',
    'ravendb_cluster_current_term': 'cluster.current.term',
    'ravendb_cluster_index': 'cluster.index',
}


gauge = {
    'ravendb_server_info': {
        'name': 'server.info',
        'type': 'gauge',
    },
    'ravendb_server_uptime_seconds': {
        'name': 'server.uptime.seconds',
        'type': 'gauge',
    },
    'ravendb_server_process_id': 'server.process.id',
    'ravendb_cpu_machine_usage': 'cpu.machine.usage',
    'ravendb_cpu_process_usage': 'cpu.process.usage',
    'ravendb_cpu_processor_count': 'cpu.processor.count',
    'ravendb_cpu_assigned_processor_count': 'cpu.assigned.processor.count',
    'ravendb_cpu_thread_pool_available_worker_threads': 'cpu.thread.pool.available.worker.threads',
    'ravendb_cpu_thread_pool_available_completion_port_threads': 'cpu.thread.pool.available.completion.port.threads',
    'ravendb_cpu_machine_io_wait': 'cpu.machine.io.wait',
    'ravendb_backup_current_number_of_running_backups': 'backup.current.number.of.running.backups',
    'ravendb_backup_max_number_of_concurrent_backups': 'backup.max.number.of.concurrent.backups',
    'ravendb_memory_allocated_bytes': 'memory.allocated.bytes',
    'ravendb_memory_installed_bytes': 'memory.installed.bytes',
    'ravendb_memory_physical_bytes': 'memory.physical.bytes',
    'ravendb_memory_low_memory_severity': 'memory.low.memory.severity',
    'ravendb_memory_total_dirty_bytes': 'memory.total.dirty.bytes',
    'ravendb_memory_total_swap_size_bytes': 'memory.total.swap.size.bytes',
    'ravendb_memory_total_swap_usage_bytes': 'memory.total.swap.usage.bytes',
    'ravendb_memory_working_set_swap_usage_bytes': 'memory.working.set.swap.usage.bytes',
    'ravendb_available_memory_for_processing_bytes': 'available.memory.for.processing.bytes',
    'ravendb_managed_memory_bytes': 'managed.memory.bytes',
    'ravendb_unmanaged_memory_bytes': 'unmanaged.memory.bytes',
    "ravendb_gc_index": 'gc.index',
    "ravendb_gc_generation": 'gc.generation',
    "ravendb_gc_compacted": 'gc.compacted',
    "ravendb_gc_concurrent": 'gc.concurrent',
    "ravendb_gc_finalization_pending_count": 'gc.finalization.pending.count',
    "ravendb_gc_fragmented_mb": 'gc.fragmented.mb',
    "ravendb_gc_heap_size_mb": 'gc.heap.size.mb',
    "ravendb_gc_high_memory_load_threshold_mb": 'gc.high.memory.load.threshold.mb',
    "ravendb_gc_memory_load_mb": 'gc.memory.load.mb',
    "ravendb_gc_pause_durations_1_seconds": 'gc.pause.durations.1.seconds',
    "ravendb_gc_pause_durations_2_seconds": 'gc.pause.durations.2.seconds',
    "ravendb_gc_pause_time_percentage": 'gc.pause.time.percentage',
    "ravendb_gc_pinned_objects_count": 'gc.pinned.objects.count',
    "ravendb_gc_promoted_mb": 'gc.promoted.mb',
    "ravendb_gc_total_available_memory_mb": 'gc.total.available.memory.mb',
    "ravendb_gc_total_committed_mb": 'gc.total.committed.mb',
    'ravendb_network_tcp_active_connections': 'network.tcp.active.connections',
    'ravendb_network_concurrent_requests_count': 'network.concurrent.requests.count',
    'ravendb_network_last_request_time_in_seconds': 'network.last.request.time.in.seconds',
    'ravendb_certificate_server_certificate_expiration_left_seconds': (
        'certificate.server.certificate.expiration.left.seconds'
    ),
    'ravendb_cluster_node_state': 'cluster.node.state',
    'ravendb_databases_loaded_count': 'databases.loaded.count',
    'ravendb_databases_total_count': 'databases.total.count',
    'ravendb_server_storage_io_read_operations': 'server.storage.io.read.operations',
    'ravendb_server_storage_io_write_operations': 'server.storage.io.write.operations',
    'ravendb_server_storage_read_throughput_bytes': 'server.storage.read.throughput.bytes',
    'ravendb_server_storage_write_throughput_bytes': 'server.storage.write.throughput.bytes',
    'ravendb_server_storage_queue_length': 'server.storage.queue.length',
    'ravendb_server_storage_total_free_space_bytes': 'server.storage.total.free.space.bytes',
    'ravendb_server_disk_system_store_used_data_file_size_bytes': 'server.disk.system.store.used.data.file.size.bytes',
    'ravendb_server_disk_system_store_total_data_file_size_bytes': (
        'server.disk.system.store.total.data.file.size.bytes'
    ),
    'ravendb_server_disk_remaining_storage_space_percentage': 'server.disk.remaining.storage.space.percentage',
    'ravendb_license_type': 'license.type',
    'ravendb_license_expiration_left_seconds': 'license.expiration.left.seconds',
    'ravendb_license_utilized_cpu_cores': 'license.utilized.cpu.cores',
    'ravendb_license_max_cores': 'license.max.cores',
    'ravendb_database_uptime_seconds': 'database.uptime.seconds',
    'ravendb_database_time_since_last_backup_seconds': 'database.time.since.last.backup.seconds',
    'ravendb_database_documents_count': 'database.documents.count',
    'ravendb_database_revisions_count': 'database.revisions.count',
    'ravendb_database_attachments_count': 'database.attachments.count',
    'ravendb_database_unique_attachments_count': 'database.unique.attachments.count',
    'ravendb_database_alerts_count': 'database.alerts.count',
    'ravendb_database_rehabs_count': 'database.rehabs.count',
    'ravendb_database_performance_hints_count': 'database.performance.hints.count',
    'ravendb_database_replication_factor': 'database.replication.factor',
    'ravendb_database_statistics_doc_puts_per_second': 'database.statistics.doc.puts.per.second',
    'ravendb_database_statistics_map_index_indexes_per_second': 'database.statistics.map.index.indexes.per.second',
    'ravendb_database_statistics_map_reduce_index_mapped_per_second': (
        'database.statistics.map.reduce.index.mapped.per.second'
    ),
    'ravendb_database_statistics_map_reduce_index_reduced_per_second': (
        'database.statistics.map.reduce.index.reduced.per.second'
    ),
    'ravendb_database_statistics_requests_per_second': 'database.statistics.requests.per.second',
    'ravendb_database_statistics_requests_count': 'database.statistics.requests.count',
    'ravendb_database_statistics_request_average_duration_seconds': (
        'database.statistics.request.average.duration.seconds'
    ),
    'ravendb_database_indexes_count': 'database.indexes.count',
    'ravendb_database_indexes_stale_count': 'database.indexes.stale.count',
    'ravendb_database_indexes_errors_count': 'database.indexes.errors.count',
    'ravendb_database_indexes_static_count': 'database.indexes.static.count',
    'ravendb_database_indexes_auto_count': 'database.indexes.auto.count',
    'ravendb_database_indexes_idle_count': 'database.indexes.idle.count',
    'ravendb_database_indexes_disabled_count': 'database.indexes.disabled.count',
    'ravendb_database_indexes_errored_count': 'database.indexes.errored.count',
    'ravendb_database_storage_documents_allocated_data_file_bytes': (
        'database.storage.documents.allocated.data.file.bytes'
    ),
    'ravendb_database_storage_documents_used_data_file_bytes': 'database.storage.documents.used.data.file.bytes',
    'ravendb_database_storage_indexes_allocated_data_file_bytes': (
        'database.storage.indexes.allocated.data.file.bytes'
    ),
    'ravendb_database_storage_indexes_used_data_file_bytes': 'database.storage.indexes.used.data.file.bytes',
    'ravendb_database_storage_total_allocated_storage_file_bytes': (
        'database.storage.total.allocated.storage.file.bytes'
    ),
    'ravendb_database_storage_total_free_space_bytes': 'database.storage.total.free.space.bytes',
    'ravendb_database_storage_io_read_operations': 'database.storage.io.read.operations',
    'ravendb_database_storage_io_write_operations': 'database.storage.io.write.operations',
    'ravendb_database_storage_read_throughput_bytes': 'database.storage.read.throughput.bytes',
    'ravendb_database_storage_write_throughput_bytes': 'database.storage.write.throughput.bytes',
    'ravendb_database_storage_queue_length': 'database.storage.queue.length',
    'ravendb_index_errors': 'index.errors',
    'ravendb_index_is_invalid': 'index.is.invalid',
    'ravendb_index_priority': 'index.priority',
    'ravendb_index_state': 'index.state',
    'ravendb_index_lock_mode': 'index.lock.mode',
    'ravendb_archived_data_processing_behavior': 'archived.data.processing.behavior',
    'ravendb_index_status': 'index.status',
    'ravendb_index_type': 'index.type',
    'ravendb_index_entries_count': 'index.entries.count',
    'ravendb_index_time_since_last_indexing_seconds': 'index.time.since.last.indexing.seconds',
    'ravendb_index_time_since_last_query_seconds': 'index.time.since.last.query.seconds',
    'ravendb_index_mapped_per_second': 'index.mapped.per.second',
    'ravendb_index_reduced_per_second': 'index.reduced.per.second',
    'ravendb_collection_documents_count': 'collection.documents.count',
    'ravendb_collection_documents_size_bytes': 'collection.documents.size.bytes',
    'ravendb_collection_revisions_size_bytes': 'collection.revisions.size.bytes',
    'ravendb_collection_tombstones_size_bytes': 'collection.tombstones.size.bytes',
    'ravendb_collection_total_size_bytes': 'collection.total.size.bytes',
}

METRIC_MAP = {**counter, **gauge}
