# (C) Datadog, Inc. 2025-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# Prometheus names are listed without the `_total` suffix, which the OpenMetrics parser strips from counters.
METRIC_MAP = {
    'kurrentdb_cache_hits_misses': 'cache_hits_misses',
    'kurrentdb_cache_resources_bytes': 'cache_resources_bytes',
    'kurrentdb_cache_resources_entries': 'cache_resources_entries',
    'kurrentdb_checkpoints': 'checkpoints',
    'kurrentdb_elections_count': 'elections_count',
    'kurrentdb_io_bytes': 'io_bytes',
    'kurrentdb_io_events': 'io_events',
    'kurrentdb_logical_chunk_read_distribution': 'logical_chunk_read_distribution',
    'kurrentdb_io_record_read_duration_seconds': 'io_record_read_duration_seconds',
    'kurrentdb_gossip_latency_seconds': 'gossip_latency_seconds',
    'kurrentdb_gossip_processing_duration_seconds': 'gossip_processing_duration_seconds',
    'kurrentdb_current_incoming_grpc_calls': 'current_incoming_grpc_calls',
    'kurrentdb_incoming_grpc_calls': 'incoming_grpc_calls',
    'kurrentdb_grpc_method_duration_seconds': 'grpc_method_duration_seconds',
    'kurrentdb_kestrel_connections': 'kestrel_connections',
    'kurrentdb_persistent_sub_connections': 'persistent_sub_connections',
    'kurrentdb_persistent_sub_parked_messages': 'persistent_sub_parked_messages',
    'kurrentdb_persistent_sub_in_flight_messages': 'persistent_sub_in_flight_messages',
    'kurrentdb_persistent_sub_oldest_parked_message_seconds': 'persistent_sub_oldest_parked_message_seconds',
    'kurrentdb_persistent_sub_items_processed': 'persistent_sub_items_processed',
    'kurrentdb_persistent_sub_last_known_event_number': 'persistent_sub_last_known_event_number',
    'kurrentdb_persistent_sub_last_known_event_commit_position': 'persistent_sub_last_known_event_commit_position',
    'kurrentdb_persistent_sub_checkpointed_event_number': 'persistent_sub_checkpointed_event_number',
    'kurrentdb_persistent_sub_checkpointed_event_commit_position': 'persistent_sub_checkpointed_event_commit_position',
    'kurrentdb_persistent_sub_parked_message_replays': 'persistent_sub_parked_message_replays',
    'kurrentdb_persistent_sub_park_message_requests': 'persistent_sub_park_message_requests',
    'kurrentdb_proc_up_time_seconds': 'proc_up_time_seconds',
    'kurrentdb_proc_cpu': 'proc_cpu',
    'kurrentdb_proc_thread_count': 'proc_thread_count',
    'kurrentdb_proc_thread_pool_pending_work_item_count': 'proc_thread_pool_pending_work_item_count',
    'kurrentdb_proc_contention_count': 'proc_contention_count',
    'kurrentdb_proc_exception_count': 'proc_exception_count',
    'kurrentdb_gc_time_in_gc': 'gc_time_in_gc',
    'kurrentdb_gc_heap_size_bytes': 'gc_heap_size_bytes',
    'kurrentdb_gc_heap_fragmentation': 'gc_heap_fragmentation',
    'kurrentdb_gc_allocated_bytes': 'gc_allocated_bytes',
    'kurrentdb_gc_pause_duration_max_seconds': 'gc_pause_duration_max_seconds',
    'kurrentdb_gc_generation_size_bytes': 'gc_generation_size_bytes',
    'kurrentdb_gc_collection_count': 'gc_collection_count',
    'kurrentdb_proc_mem_bytes': 'proc_mem_bytes',
    'kurrentdb_disk_io_bytes': 'disk_io_bytes',
    'kurrentdb_disk_io_operations': 'disk_io_operations',
    'kurrentdb_projection_events_processed_after_restart': 'projection_events_processed_after_restart',
    'kurrentdb_projection_progress': 'projection_progress',
    'kurrentdb_projection_running': 'projection_running',
    'kurrentdb_projection_status': 'projection_status',
    'kurrentdb_projection_state_size': 'projection_state_size',
    'kurrentdb_projection_state_size_bound': 'projection_state_size_bound',
    'kurrentdb_projection_state_serialization_duration_max_seconds': 'projection_state_serialization_duration_max_seconds',  # noqa: E501
    'kurrentdb_projection_execution_duration_max_seconds': 'projection_execution_duration_max_seconds',
    'kurrentdb_projection_execution_duration_seconds': 'projection_execution_duration_seconds',
    'kurrentdb_queue_queueing_duration_max_seconds': 'queue_queueing_duration_max_seconds',
    'kurrentdb_queue_processing_duration_seconds': 'queue_processing_duration_seconds',
    'kurrentdb_statuses': 'statuses',
    'kurrentdb_writer_flush_size_max': 'writer_flush_size_max',
    'kurrentdb_writer_flush_duration_max_seconds': 'writer_flush_duration_max_seconds',
    'kurrentdb_sys_load_avg': 'sys_load_avg',
    'kurrentdb_sys_cpu': 'sys_cpu',
    'kurrentdb_sys_mem_bytes': 'sys_mem_bytes',
    'kurrentdb_sys_disk_bytes': 'sys_disk_bytes',
    'kurrentdb_indexes_secondary_gap_bytes': 'indexes_secondary_gap_bytes',
    'kurrentdb_indexes_secondary_lag_seconds': 'indexes_secondary_lag_seconds',
    'kurrentdb_persistent_sub_parked_message_truncations': 'persistent_sub_parked_message_truncations',
    'aspnetcore_authentication_authenticate_duration_seconds': 'aspnetcore_authentication_authenticate_duration_seconds',  # noqa: E501
    'aspnetcore_memory_pool_allocated_bytes': 'aspnetcore_memory_pool_allocated_bytes',
    'aspnetcore_memory_pool_evicted_bytes': 'aspnetcore_memory_pool_evicted_bytes',
    'aspnetcore_memory_pool_pooled_bytes': 'aspnetcore_memory_pool_pooled_bytes',
    'aspnetcore_memory_pool_rented_bytes': 'aspnetcore_memory_pool_rented_bytes',
    'aspnetcore_routing_match_attempts': 'aspnetcore_routing_match_attempts',
    'http_server_active_requests': 'http_server_active_requests',
    'http_server_request_duration_seconds': 'http_server_request_duration_seconds',
    'kestrel_active_connections': 'kestrel_active_connections',
    'kestrel_connection_duration_seconds': 'kestrel_connection_duration_seconds',
    'kestrel_queued_connections': 'kestrel_queued_connections',
    'messaging_kurrent_consumer_message_count': 'messaging_kurrent_consumer_message_count',
    'messaging_kurrent_producer_message_count': 'messaging_kurrent_producer_message_count',
    'messaging_kurrent_producer_produce_duration_seconds': 'messaging_kurrent_producer_produce_duration_seconds',
    'messaging_kurrent_producer_queue_length': 'messaging_kurrent_producer_queue_length',
}
