# (C) Datadog, Inc. 2019-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

APPLICATION_METRICS = {
    'argocd_app_info': 'app_info',
    'argocd_app_k8s_request_total': 'app_k8s_request_total',
    'argocd_app_reconcile_bucket': 'app_reconcile_bucket',
    'argocd_app_reconcile_sum': 'app_reconcile_sum',
    'argocd_app_reconcile_count': 'app_reconcile_count',
    'argocd_app_sync_total': 'app_sync_total',
    'argocd_cluster_api_resource_objects': 'cluster_api_resource_objects',
    'argocd_cluster_api_resources': 'cluster_api_resources',
    'argocd_cluster_cache_age_seconds': 'cluster_cache_age_seconds',
    'argocd_cluster_events_total': 'cluster_events_total',
    'argocd_cluster_info': 'cluster_info',
    'argocd_kubectl_exec_pending': 'kubectl_exec_pending',
    'argocd_kubectl_exec_total': 'kubectl_exec_total',
    'argocd_redis_request_duration_bucket': 'redis_request_duration_bucket',
    'argocd_redis_request_duration_sum': 'redis_request_duration_sum',
    'argocd_redis_request_duration_count': 'redis_request_duration_count',
    'go_gc_duration_seconds': 'go_gc_duration_seconds',
    'go_goroutines': 'go_goroutines',
    'go_info': 'go_info',
    'go_memstats_alloc_bytes': 'go_memstats_alloc_bytes',
    'go_memstats_alloc_bytes_total': 'go_memstats_alloc_bytes_total',
    'go_memstats_buck_hash_sys_bytes': 'go_memstats_buck_hash_sys_bytes',
    'go_memstats_frees_total': 'go_memstats_frees_total',
    'go_memstats_gc_cpu_fraction': 'go_memstats_gc_cpu_fraction',
    'go_memstats_gc_sys_bytes': 'go_memstats_gc_sys_bytes',
    'go_memstats_heap_alloc_bytes': 'go_memstats_heap_alloc_bytes',
    'go_memstats_heap_idle_bytes': 'go_memstats_heap_idle_bytes ',
    'go_memstats_heap_inuse_bytes': 'go_memstats_heap_inuse_bytes ',
    'go_memstats_heap_objects': 'go_memstats_heap_objects',
    'go_memstats_heap_released_bytes': 'go_memstats_heap_released_bytes',
    'go_memstats_heap_sys_bytes': 'go_memstats_heap_sys_bytes',
    'go_memstats_last_gc_time_seconds': 'go_memstats_last_gc_time_seconds',
    'go_memstats_lookups_total': 'go_memstats_lookups_total',
    'go_memstats_mallocs_total': 'go_memstats_mallocs_total',
    'go_memstats_mcache_inuse_bytes': 'go_memstats_mcache_inuse_bytes',
    'go_memstats_mcache_sys_bytes': 'go_memstats_mcache_sys_bytes',
    'go_memstats_mspan_inuse_bytes': 'go_memstats_mspan_inuse_bytes',
    'go_memstats_mspan_sys_bytes': 'go_memstats_mspan_sys_bytes',
    'go_memstats_next_gc_bytes': 'go_memstats_next_gc_bytes',
    'go_memstats_other_sys_bytes': 'go_memstats_other_sys_bytes',
    'go_memstats_stack_inuse_bytes': 'go_memstats_stack_inuse_bytes',
    'go_memstats_stack_sys_bytes': 'go_memstats_stack_sys_bytes',
    'go_memstats_sys_bytes': 'go_memstats_sys_bytes',
    'go_threads': 'go_threads',
    'process_cpu_seconds_total': 'process_cpu_seconds_total',
    'process_max_fds': 'process_max_fds',
    'process_open_fds': 'process_open_fds',
    'process_resident_memory_bytes': 'process_resident_memory_bytes',
    'process_start_time_seconds': 'process_start_time_seconds',
    'process_virtual_memory_bytes': 'process_virtual_memory_bytes',
    'process_virtual_memory_max_bytes': 'process_virtual_memory_max_bytes',
}

