import os

from datadog_checks.dev import get_docker_hostname

HOST = get_docker_hostname()
PORT = 9644

REDPANDA_VERSION = os.getenv('REDPANDA_VERSION')

CHECK_NAME = 'redpanda'
NAMESPACE = 'redpanda.'

INSTANCE_METRIC_GROUP_MAP = {
    'redpanda.application': [
        'redpanda.application.uptime',
        'redpanda.application.build',
    ],
    'redpanda.alien': [
        'redpanda.alien.receive_batch_queue_length',
        'redpanda.alien.total_received_messages',
        'redpanda.alien.total_sent_messages',
    ],
    'redpanda.cluster': [
        'redpanda.cluster.partition_committed_offset',
        'redpanda.cluster.partition_end_offset',
        'redpanda.cluster.partition_high_watermark',
        'redpanda.cluster.partition_last_stable_offset',
        'redpanda.cluster.partition_leader',
        'redpanda.cluster.partition_leader_id',
        'redpanda.cluster.partition_records_fetched',
        'redpanda.cluster.partition_records_produced',
        'redpanda.cluster.partition_under_replicated_replicas',
    ],
    'redpanda.httpd': [
        'redpanda.httpd.connections_current',
        'redpanda.httpd.connections_total',
        'redpanda.httpd.read_errors',
        'redpanda.httpd.reply_errors',
        'redpanda.httpd.requests_served',
    ],
    'redpanda.internal_rpc': [
        'redpanda.internal_rpc.active_connections',
        'redpanda.internal_rpc.connection_close_errors',
        'redpanda.internal_rpc.connects',
        'redpanda.internal_rpc.consumed_mem_bytes',
        'redpanda.internal_rpc.corrupted_headers',
        'redpanda.internal_rpc.dispatch_handler_latency.sum',
        'redpanda.internal_rpc.dispatch_handler_latency.count',
        'redpanda.internal_rpc.max_service_mem_bytes',
        'redpanda.internal_rpc.method_not_found_errors',
        'redpanda.internal_rpc.received_bytes',
        'redpanda.internal_rpc.requests_blocked_memory',
        'redpanda.internal_rpc.requests_completed',
        'redpanda.internal_rpc.requests_pending',
        'redpanda.internal_rpc.sent_bytes',
        'redpanda.internal_rpc.service_errors',
    ],
    'redpanda.io_queue': [
        'redpanda.io_queue.delay',
        'redpanda.io_queue.queue_length',
        'redpanda.io_queue.shares',
        'redpanda.io_queue.total_bytes',
        'redpanda.io_queue.total_delay_sec',
        'redpanda.io_queue.total_operations',
    ],
    'redpanda.kafka': [
        'redpanda.kafka.fetch_sessions_cache_mem_usage_bytes',
        'redpanda.kafka.fetch_sessions_cache_sessions_count',
        'redpanda.kafka.latency_fetch_latency_us.sum',
        'redpanda.kafka.latency_fetch_latency_us.count',
        'redpanda.kafka.latency_produce_latency_us.sum',
        'redpanda.kafka.latency_produce_latency_us.count',
        'redpanda.kafka.rpc_active_connections',
        'redpanda.kafka.rpc_connection_close_errors',
        'redpanda.kafka.rpc_connects',
        'redpanda.kafka.rpc_consumed_mem_bytes',
        'redpanda.kafka.rpc_corrupted_headers',
        'redpanda.kafka.rpc_dispatch_handler_latency.sum',
        'redpanda.kafka.rpc_dispatch_handler_latency.count',
        'redpanda.kafka.rpc_max_service_mem_bytes',
        'redpanda.kafka.rpc_method_not_found_errors',
        'redpanda.kafka.rpc_received_bytes',
        'redpanda.kafka.rpc_requests_blocked_memory',
        'redpanda.kafka.rpc_requests_completed',
        'redpanda.kafka.rpc_requests_pending',
        'redpanda.kafka.rpc_sent_bytes',
        'redpanda.kafka.rpc_service_errors',
    ],
    'redpanda.leader': [
        'redpanda.leader.balancer_leader_transfer_error',
        'redpanda.leader.balancer_leader_transfer_no_improvement',
        'redpanda.leader.balancer_leader_transfer_succeeded',
        'redpanda.leader.balancer_leader_transfer_timeout',
    ],
    'redpanda.memory': [
        'redpanda.memory.allocated_memory',
        'redpanda.memory.cross_cpu_free_operations',
        'redpanda.memory.free_memory',
        'redpanda.memory.free_operations',
        'redpanda.memory.malloc_live_objects',
        'redpanda.memory.malloc_operations',
        'redpanda.memory.reclaims_operations',
        'redpanda.memory.total_memory',
    ],
    'redpanda.pandaproxy': [
        'redpanda.pandaproxy.request_latency.sum',
        'redpanda.pandaproxy.request_latency.count',
    ],
    'redpanda.raft': [
        'redpanda.raft.done_replicate_requests',
        'redpanda.raft.group_count',
        'redpanda.raft.heartbeat_requests_errors',
        'redpanda.raft.leader_for',
        'redpanda.raft.leadership_changes',
        'redpanda.raft.log_flushes',
        'redpanda.raft.log_truncations',
        'redpanda.raft.received_append_requests',
        'redpanda.raft.received_vote_requests',
        'redpanda.raft.recovery_requests_errors',
        'redpanda.raft.replicate_ack_all_requests',
        'redpanda.raft.replicate_ack_leader_requests',
        'redpanda.raft.replicate_ack_none_requests',
        'redpanda.raft.replicate_request_errors',
        'redpanda.raft.sent_vote_requests',
    ],
    'redpanda.reactor': [
        'redpanda.reactor.abandoned_failed_futures',
        'redpanda.reactor.aio_bytes_read',
        'redpanda.reactor.aio_bytes_write',
        'redpanda.reactor.aio_errors',
        'redpanda.reactor.aio_reads',
        'redpanda.reactor.aio_writes',
        'redpanda.reactor.cpp_exceptions',
        'redpanda.reactor.cpu_busy_ms',
        'redpanda.reactor.cpu_steal_time_ms',
        'redpanda.reactor.fstream_read_bytes',
        'redpanda.reactor.fstream_read_bytes_blocked',
        'redpanda.reactor.fstream_reads',
        'redpanda.reactor.fstream_reads_ahead_bytes_discarded',
        'redpanda.reactor.fstream_reads_aheads_discarded',
        'redpanda.reactor.fstream_reads_blocked',
        'redpanda.reactor.fsyncs',
        'redpanda.reactor.io_threaded_fallbacks',
        'redpanda.reactor.logging_failures',
        'redpanda.reactor.polls',
        'redpanda.reactor.tasks_pending',
        'redpanda.reactor.tasks_processed',
        'redpanda.reactor.timers_pending',
        'redpanda.reactor.utilization',
    ],
    'redpanda.rpc_client': [
        'redpanda.rpc_client.active_connections',
        'redpanda.rpc_client.client_correlation_errors',
        'redpanda.rpc_client.connection_errors',
        'redpanda.rpc_client.connects',
        'redpanda.rpc_client.corrupted_headers',
        'redpanda.rpc_client.in_bytes',
        'redpanda.rpc_client.out_bytes',
        'redpanda.rpc_client.read_dispatch_errors',
        'redpanda.rpc_client.request_errors',
        'redpanda.rpc_client.request_timeouts',
        'redpanda.rpc_client.requests',
        'redpanda.rpc_client.requests_blocked_memory',
        'redpanda.rpc_client.requests_pending',
        'redpanda.rpc_client.server_correlation_errors',
    ],
    'redpanda.scheduler': [
        'redpanda.scheduler.queue_length',
        'redpanda.scheduler.runtime_ms',
        'redpanda.scheduler.shares',
        'redpanda.scheduler.starvetime_ms',
        'redpanda.scheduler.tasks_processed',
        'redpanda.scheduler.time_spent_on_task_quota_violations_ms',
        'redpanda.scheduler.waittime_ms',
    ],
    'redpanda.stall': [
        'redpanda.stall.detector_reported',
    ],
    'redpanda.storage': [
        'redpanda.storage.compaction_backlog_controller_backlog_size',
        'redpanda.storage.compaction_backlog_controller_error',
        'redpanda.storage.compaction_backlog_controller_shares',
        'redpanda.storage.kvstore_cached_bytes',
        'redpanda.storage.kvstore_entries_fetched',
        'redpanda.storage.kvstore_entries_removed',
        'redpanda.storage.kvstore_entries_written',
        'redpanda.storage.kvstore_key_count',
        'redpanda.storage.kvstore_segments_rolled',
        'redpanda.storage.log_batch_parse_errors',
        'redpanda.storage.log_batch_write_errors',
        'redpanda.storage.log_batches_read',
        'redpanda.storage.log_batches_written',
        'redpanda.storage.log_cache_hits',
        'redpanda.storage.log_cache_misses',
        'redpanda.storage.log_cached_batches_read',
        'redpanda.storage.log_cached_read_bytes',
        'redpanda.storage.log_compacted_segment',
        'redpanda.storage.log_compaction_ratio',
        'redpanda.storage.log_corrupted_compaction_indices',
        'redpanda.storage.log_log_segments_active',
        'redpanda.storage.log_log_segments_created',
        'redpanda.storage.log_log_segments_removed',
        'redpanda.storage.log_partition_size',
        'redpanda.storage.log_read_bytes',
        'redpanda.storage.log_readers_added',
        'redpanda.storage.log_readers_evicted',
        'redpanda.storage.log_written_bytes',
    ],
}
# fmt: on

INSTANCE_DEFAULT_GROUPS = [
    'redpanda.application',
    'redpanda.cluster',
    'redpanda.httpd',
    'redpanda.kafka',
    'redpanda.leader',
    'redpanda.pandaproxy',
    'redpanda.reactor',
    'redpanda.storage',
]

INSTANCE_ADDITIONAL_GROUPS = [
    'redpanda.alien',
    'redpanda.internal_rpc',
    'redpanda.io_queue',
    'redpanda.memory',
    'redpanda.raft',
    'redpanda.rpc_client',
    'redpanda.scheduler',
    'redpanda.stall',
]


def get_metrics(metric_groups):
    """Given a list of metric groups, return single consolidated list"""
    return sorted(m for g in metric_groups for m in INSTANCE_METRIC_GROUP_MAP[g])


INSTANCE_DEFAULT_METRICS = get_metrics(INSTANCE_DEFAULT_GROUPS)
INSTANCE_ADDITIONAL_METRICS = get_metrics(INSTANCE_ADDITIONAL_GROUPS)
