DEFAULT_METRICS = {
    "app_status_recovery_mode": "app.status.recovery.mode",
    "collections_total": "collections.total",
    "collections_vector_total": "collections.vector.total",
    "collections_full_total": "collections.full.total",
    "collections_aggregated_total": "collections.aggregated.total",
    "rest_responses": "rest.responses",
    "rest_responses_fail": "rest.responses.fail",
    "rest_responses_avg_duration_seconds": "rest.responses.avg.duration.seconds",
    "rest_responses_min_duration_seconds": "rest.responses.min.duration.seconds",
    "rest_responses_max_duration_seconds": "rest.responses.max.duration.seconds",
    "grpc_responses": "grpc.responses",
    "grpc_responses_fail": "grpc.responses.fail",
    "grpc_responses_avg_duration_seconds": "grpc.responses.avg.duration.seconds",
    "grpc_responses_min_duration_seconds": "grpc.responses.min.duration.seconds",
    "grpc_responses_max_duration_seconds": "grpc.responses.max.duration.seconds",
    "cluster_enabled": "cluster.enabled",
    "cluster_peers_total": "cluster.peers.total",
    "cluster_term": "cluster.term",
    "cluster_commit": "cluster.commit",
    "cluster_pending_operations_total": "cluster.pending.operations.total",
    "cluster_voter": "cluster.voter",
}
