# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def shared_skip_proxy():
    return False


def shared_timeout():
    return 10


def instance_allow_redirects():
    return True


def instance_auth_type():
    return 'basic'


def instance_bearer_token_refresh_interval():
    return 60


def instance_disable_generic_tags():
    return False


def instance_dm_master_metric_url():
    return 'http://localhost:8261/metrics'


def instance_dm_worker_metric_url():
    return 'http://localhost:8262/metrics'


def instance_empty_default_hostname():
    return False


def instance_health_service_check():
    return True


def instance_kerberos_auth():
    return 'disabled'


def instance_kerberos_delegate():
    return False


def instance_kerberos_force_initiate():
    return False


def instance_log_requests():
    return False


def instance_min_collection_interval():
    return 15


def instance_namespace():
    return 'service'


def instance_persist_connections():
    return False


def instance_pump_metric_url():
    return 'http://localhost:8250/metrics'


def instance_request_size():
    return 10


def instance_send_distribution_counts_as_monotonic():
    return False


def instance_send_distribution_sums_as_monotonic():
    return False


def instance_send_histograms_buckets():
    return True


def instance_send_monotonic_counter():
    return True


def instance_send_monotonic_with_gauge():
    return False


def instance_skip_proxy():
    return False


def instance_ticdc_metric_url():
    return 'http://localhost:8301/metrics'


def instance_tidb_metric_url():
    return 'http://localhost:10080/metrics'


def instance_tiflash_metric_url():
    return 'http://localhost:8234/metrics'


def instance_tiflash_proxy_metric_url():
    return 'http://localhost:20292/metrics'


def instance_tikv_metric_url():
    return 'http://localhost:20180/metrics'


def instance_timeout():
    return 10


def instance_tls_ignore_warning():
    return False


def instance_tls_use_host_header():
    return False


def instance_tls_verify():
    return True


def instance_use_legacy_auth_encoding():
    return True


def instance_use_process_start_time():
    return False
