import os

from datadog_checks.dev import get_docker_hostname

VERSION = os.getenv('rdsc.redis_VERSION')
CHECK = 'rdsc.redis_cloud'

PORT = 8070
CONFTEST_PORT = 8443
HOST = get_docker_hostname()

ENDPOINT = "https://{}:{}/metrics".format(HOST, PORT)
INSTANCE = {'openmetrics_endpoint': ENDPOINT}

CONFTEST = "https://{}:{}/#/bootstrap".format(HOST, CONFTEST_PORT)

ERSATZ_INSTANCE = {'openmetrics_endpoint': "https://localhost:8071/metrics", 'tags': ['instance']}

EPHEMERAL = [
    "rdsc.bdb_avg_read_latency",
    "rdsc.bdb_avg_read_latency_max",
    "rdsc.bdb_avg_write_latency",
    "rdsc.bdb_avg_write_latency_max",
    'rdsc.no_of_expires',
    'rdsc.node_available_flash',
    'rdsc.node_available_flash_no_overbooking',
    'rdsc.node_up',
    'rdsc.redis_blocking_reads',
    'rdsc.redis_blocking_writes',
    'rdsc.redis_db0_avg_ttl',
    'rdsc.redis_db0_expires',
    'rdsc.redis_db0_keys',
    'rdsc.redis_mem_fragmentation_ratio',
    'rdsc.redis_used_disk',
    'rdsc.bdb_replicaof_syncer_ingress_bytes',
    'rdsc.bdb_replicaof_syncer_ingress_bytes_decompressed',
    'rdsc.bdb_replicaof_syncer_local_ingress_lag_time',
    'rdsc.bdb_replicaof_syncer_status',
]

# cloud metrics use the namespace 'rdsc'
METRICS_MAP = {
    'RDSC.DATABASE': [
        'rdsc.bdb_avg_latency',
        'rdsc.bdb_avg_latency_max',
        'rdsc.bdb_avg_read_latency',
        'rdsc.bdb_avg_read_latency_max',
        'rdsc.bdb_avg_write_latency',
        'rdsc.bdb_avg_write_latency_max',
        'rdsc.bdb_conns',
        'rdsc.bdb_egress_bytes',
        'rdsc.bdb_egress_bytes_max',
        'rdsc.bdb_evicted_objects',
        'rdsc.bdb_evicted_objects_max',
        'rdsc.bdb_expired_objects',
        'rdsc.bdb_expired_objects_max',
        'rdsc.bdb_fork_cpu_system',
        'rdsc.bdb_fork_cpu_system_max',
        'rdsc.bdb_fork_cpu_user',
        'rdsc.bdb_fork_cpu_user_max',
        'rdsc.bdb_ingress_bytes',
        'rdsc.bdb_ingress_bytes_max',
        'rdsc.bdb_instantaneous_ops_per_sec',
        'rdsc.bdb_main_thread_cpu_system',
        'rdsc.bdb_main_thread_cpu_system_max',
        'rdsc.bdb_main_thread_cpu_user',
        'rdsc.bdb_main_thread_cpu_user_max',
        'rdsc.bdb_mem_frag_ratio',
        'rdsc.bdb_mem_size_lua',
        'rdsc.bdb_memory_limit',
        'rdsc.bdb_monitor_sessions_count',
        'rdsc.bdb_no_of_keys',
        'rdsc.bdb_other_req',
        'rdsc.bdb_other_req_max',
        'rdsc.bdb_other_res',
        'rdsc.bdb_other_res_max',
        'rdsc.bdb_pubsub_channels',
        'rdsc.bdb_pubsub_channels_max',
        'rdsc.bdb_pubsub_patterns',
        'rdsc.bdb_pubsub_patterns_max',
        'rdsc.bdb_read_hits',
        'rdsc.bdb_read_hits_max',
        'rdsc.bdb_read_misses',
        'rdsc.bdb_read_misses_max',
        'rdsc.bdb_read_req',
        'rdsc.bdb_read_req_max',
        'rdsc.bdb_read_res',
        'rdsc.bdb_read_res_max',
        'rdsc.bdb_shard_cpu_system',
        'rdsc.bdb_shard_cpu_system_max',
        'rdsc.bdb_shard_cpu_user',
        'rdsc.bdb_shard_cpu_user_max',
        'rdsc.bdb_total_connections_received',
        'rdsc.bdb_total_connections_received_max',
        'rdsc.bdb_total_req',
        'rdsc.bdb_total_req_max',
        'rdsc.bdb_total_res',
        'rdsc.bdb_total_res_max',
        'rdsc.bdb_up',
        'rdsc.bdb_used_memory',
        'rdsc.bdb_write_hits',
        'rdsc.bdb_write_hits_max',
        'rdsc.bdb_write_misses',
        'rdsc.bdb_write_misses_max',
        'rdsc.bdb_write_req',
        'rdsc.bdb_write_req_max',
        'rdsc.bdb_write_res',
        'rdsc.bdb_write_res_max',
    ],
    'RDSC.NODE': [
        'rdsc.no_of_expires',
        'rdsc.node_available_memory',
        'rdsc.node_available_memory_no_overbooking',
        'rdsc.node_avg_latency',
        'rdsc.node_conns',
        'rdsc.node_cpu_idle',
        'rdsc.node_cpu_idle_max',
        'rdsc.node_cpu_idle_median',
        'rdsc.node_cpu_idle_min',
        'rdsc.node_cpu_iowait',
        'rdsc.node_cpu_iowait_max',
        'rdsc.node_cpu_iowait_median',
        'rdsc.node_cpu_iowait_min',
        'rdsc.node_cpu_irqs',
        'rdsc.node_cpu_irqs_max',
        'rdsc.node_cpu_irqs_median',
        'rdsc.node_cpu_irqs_min',
        'rdsc.node_cpu_nice',
        'rdsc.node_cpu_nice_max',
        'rdsc.node_cpu_nice_median',
        'rdsc.node_cpu_nice_min',
        'rdsc.node_cpu_steal',
        'rdsc.node_cpu_steal_max',
        'rdsc.node_cpu_steal_median',
        'rdsc.node_cpu_steal_min',
        'rdsc.node_cpu_system',
        'rdsc.node_cpu_system_max',
        'rdsc.node_cpu_system_median',
        'rdsc.node_cpu_system_min',
        'rdsc.node_cpu_user',
        'rdsc.node_cpu_user_max',
        'rdsc.node_cpu_user_median',
        'rdsc.node_cpu_user_min',
        'rdsc.node_cur_aof_rewrites',
        'rdsc.node_egress_bytes',
        'rdsc.node_egress_bytes_max',
        'rdsc.node_egress_bytes_median',
        'rdsc.node_egress_bytes_min',
        'rdsc.node_ephemeral_storage_avail',
        'rdsc.node_ephemeral_storage_free',
        'rdsc.node_free_memory',
        'rdsc.node_ingress_bytes',
        'rdsc.node_ingress_bytes_max',
        'rdsc.node_ingress_bytes_median',
        'rdsc.node_ingress_bytes_min',
        'rdsc.node_persistent_storage_avail',
        'rdsc.node_persistent_storage_free',
        'rdsc.node_provisional_memory',
        'rdsc.node_provisional_memory_no_overbooking',
        'rdsc.node_total_req',
        'rdsc.node_up',
    ],
    'RDSC.SHARD': [
        'rdsc.redis_active_defrag_running',
        'rdsc.redis_allocator_active',
        'rdsc.redis_allocator_allocated',
        'rdsc.redis_allocator_resident',
        'rdsc.redis_aof_last_cow_size',
        'rdsc.redis_aof_rewrite_in_progress',
        'rdsc.redis_aof_rewrites',
        'rdsc.redis_aof_delayed_fsync',
        'rdsc.redis_blocked_clients',
        'rdsc.redis_blocking_reads',
        'rdsc.redis_blocking_writes',
        'rdsc.redis_connected_clients',
        'rdsc.redis_connected_slaves',
        'rdsc.redis_db0_avg_ttl',
        'rdsc.redis_db0_expires',
        'rdsc.redis_db0_keys',
        'rdsc.redis_evicted_keys',
        'rdsc.redis_expire_cycle_cpu_milliseconds',
        'rdsc.redis_expired_keys',
        'rdsc.redis_forwarding_state',
        'rdsc.redis_keys_trimmed',
        'rdsc.redis_keyspace_read_hits',
        'rdsc.redis_keyspace_read_misses',
        'rdsc.redis_keyspace_write_hits',
        'rdsc.redis_keyspace_write_misses',
        'rdsc.redis_master_link_status',
        'rdsc.redis_master_repl_offset',
        'rdsc.redis_master_sync_in_progress',
        'rdsc.redis_max_process_mem',
        'rdsc.redis_maxmemory',
        'rdsc.redis_mem_aof_buffer',
        'rdsc.redis_mem_clients_normal',
        'rdsc.redis_mem_clients_slaves',
        'rdsc.redis_mem_fragmentation_ratio',
        'rdsc.redis_mem_not_counted_for_evict',
        'rdsc.redis_mem_replication_backlog',
        'rdsc.redis_module_fork_in_progress',
        'rdsc.redis_process_cpu_system_seconds_total',
        'rdsc.redis_process_cpu_usage_percent',
        'rdsc.redis_process_cpu_user_seconds_total',
        'rdsc.redis_process_main_thread_cpu_system_seconds_total',
        'rdsc.redis_process_main_thread_cpu_user_seconds_total',
        'rdsc.redis_process_max_fds',
        'rdsc.redis_process_open_fds',
        'rdsc.redis_process_resident_memory_bytes',
        'rdsc.redis_process_start_time_seconds',
        'rdsc.redis_process_virtual_memory_bytes',
        'rdsc.redis_rdb_bgsave_in_progress',
        'rdsc.redis_rdb_last_cow_size',
        'rdsc.redis_rdb_saves',
        'rdsc.redis_repl_touch_bytes',
        'rdsc.redis_total_commands_processed',
        'rdsc.redis_total_connections_received',
        'rdsc.redis_total_net_input_bytes',
        'rdsc.redis_total_net_output_bytes',
        'rdsc.redis_up',
        'rdsc.redis_used_disk',
        'rdsc.redis_used_memory',
    ],
    'RDSC.REPLICATION': [
        'rdsc.bdb_crdt_syncer_ingress_bytes',
        'rdsc.bdb_crdt_syncer_ingress_bytes_decompressed',
        'rdsc.bdb_crdt_syncer_local_ingress_lag_time',
        'rdsc.bdb_crdt_syncer_status',
        'rdsc.bdb_crdt_syncer_egress_bytes',
        'rdsc.bdb_crdt_syncer_egress_bytes_decompressed',
        'rdsc.bdb_crdt_syncer_egress_bytes_decompressed_max',
        'rdsc.bdb_crdt_syncer_egress_bytes_max',
        'rdsc.bdb_replicaof_syncer_ingress_bytes',
        'rdsc.bdb_replicaof_syncer_ingress_bytes_decompressed',
        'rdsc.bdb_replicaof_syncer_local_ingress_lag_time',
        'rdsc.bdb_replicaof_syncer_status',
    ],
    'RDSC.SHARDREPL': [
        'rdsc.redis_crdt_backlog_histlen',
        'rdsc.redis_crdt_backlog_idx',
        'rdsc.redis_crdt_backlog_master_offset',
        'rdsc.redis_crdt_backlog_offset',
        'rdsc.redis_crdt_backlog_refs',
        'rdsc.redis_crdt_backlog_size',
        'rdsc.redis_crdt_clock',
        'rdsc.redis_crdt_effect_reqs',
        'rdsc.redis_crdt_gc_attempted',
        'rdsc.redis_crdt_gc_collected',
        'rdsc.redis_crdt_gc_elements_attempted',
        'rdsc.redis_crdt_gc_elements_collected',
        'rdsc.redis_crdt_gc_pending',
        'rdsc.redis_crdt_gc_skipped',
        'rdsc.redis_crdt_key_headers',
        'rdsc.redis_crdt_list_trimmed_vertices',
        'rdsc.redis_crdt_merge_reqs',
        'rdsc.redis_crdt_oom_latch',
        'rdsc.redis_crdt_ovc_filtered_effect_reqs',
        'rdsc.redis_crdt_peer_dst_id',
        'rdsc.redis_crdt_peer_id',
        'rdsc.redis_crdt_peer_lag',
        'rdsc.redis_crdt_peer_offset',
        'rdsc.redis_crdt_peer_peer_state',
        'rdsc.redis_crdt_pending_list_trimmed_vertices',
        'rdsc.redis_crdt_raw_dbsize',
        'rdsc.redis_crdt_replica_config_version',
        'rdsc.redis_crdt_replica_max_ops_lag',
        'rdsc.redis_crdt_replica_min_ops_lag',
        'rdsc.redis_crdt_replica_shards',
        'rdsc.redis_crdt_replica_slot_coverage_by_any_ovc',
        'rdsc.redis_crdt_replica_slot_coverage_by_only_ovc',
        'rdsc.redis_crdt_replica_slots',
        'rdsc.redis_crdt_stale_replica',
        'rdsc.redis_crdt_ts_key_headers',
    ],
    'RDSC.PROXY': [
        'rdsc.dmcproxy_process_cpu_system_seconds_total',
        'rdsc.dmcproxy_process_cpu_usage_percent',
        'rdsc.dmcproxy_process_cpu_user_seconds_total',
        'rdsc.dmcproxy_process_main_thread_cpu_system_seconds_total',
        'rdsc.dmcproxy_process_main_thread_cpu_user_seconds_total',
        'rdsc.dmcproxy_process_max_fds',
        'rdsc.dmcproxy_process_open_fds',
        'rdsc.dmcproxy_process_resident_memory_bytes',
        'rdsc.dmcproxy_process_start_time_seconds',
        'rdsc.dmcproxy_process_virtual_memory_bytes',
    ],
    'RDSC.LISTENER': [
        'rdsc.listener_acc_latency_total',
        'rdsc.listener_acc_latency_max_total',
        'rdsc.listener_acc_other_latency',
        'rdsc.listener_acc_other_latency_max',
        'rdsc.listener_acc_read_latency',
        'rdsc.listener_acc_read_latency_max',
        'rdsc.listener_acc_write_latency',
        'rdsc.listener_acc_write_latency_max',
        'rdsc.listener_auth_cmds',
        'rdsc.listener_auth_cmds_max',
        'rdsc.listener_auth_errors',
        'rdsc.listener_auth_errors_max',
        'rdsc.listener_cmd_flush',
        'rdsc.listener_cmd_flush_max',
        'rdsc.listener_cmd_get',
        'rdsc.listener_cmd_get_max',
        'rdsc.listener_cmd_set',
        'rdsc.listener_cmd_set_max',
        'rdsc.listener_cmd_touch',
        'rdsc.listener_cmd_touch_max',
        'rdsc.listener_conns',
        'rdsc.listener_egress_bytes',
        'rdsc.listener_egress_bytes_max',
        'rdsc.listener_ingress_bytes',
        'rdsc.listener_ingress_bytes_max',
        'rdsc.listener_last_req_time',
        'rdsc.listener_last_res_time',
        'rdsc.listener_max_connections_exceeded',
        'rdsc.listener_max_connections_exceeded_max',
        'rdsc.listener_monitor_sessions_count',
        'rdsc.listener_other_req',
        'rdsc.listener_other_req_max',
        'rdsc.listener_other_res',
        'rdsc.listener_other_res_max',
        'rdsc.listener_other_started_res',
        'rdsc.listener_other_started_res_max',
        'rdsc.listener_read_req',
        'rdsc.listener_read_req_max',
        'rdsc.listener_read_res',
        'rdsc.listener_read_res_max',
        'rdsc.listener_read_started_res',
        'rdsc.listener_read_started_res_max',
        'rdsc.listener_total_connections_received',
        'rdsc.listener_total_connections_received_max',
        'rdsc.listener_total_req',
        'rdsc.listener_total_req_max',
        'rdsc.listener_total_res',
        'rdsc.listener_total_res_max',
        'rdsc.listener_total_started_res',
        'rdsc.listener_total_started_res_max',
        'rdsc.listener_write_req',
        'rdsc.listener_write_req_max',
        'rdsc.listener_write_res',
    ],
    'RDSC.BIGSTORE': [
        'rdsc.node_bigstore_free',
        'rdsc.node_bigstore_iops',
        'rdsc.node_bigstore_kv_ops',
        'rdsc.node_bigstore_throughput',
    ],
    'RDSC.FLASH': [
        'rdsc.node_available_flash',
        'rdsc.node_available_flash_no_overbooking',
        'rdsc.node_provisional_flash',
        'rdsc.node_provisional_flash_no_overbooking',
    ],
}


DEFAULT_METRICS = [
    'RDSC.DATABASE',
    'RDSC.SHARD',
    'RDSC.LISTENER',
    'RDSC.PROXY',
]

ADDITIONAL_METRICS = [
    'RDSC.REPLICATION',
    'RDSC.SHARDREPL',
    'RDSC.BIGSTORE',
    'RDSC.FLASH',
    'RDSC.NODE',
]


def get_metrics(metric_groups):
    return sorted(m for g in metric_groups for m in DEFAULT_METRICS[g])
