# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_host():
    return 'foo.example.com'


def instance_interface():
    return 'eth0'


def instance_ip():
    return '1.2.3.4'


def instance_min_collection_interval():
    return 15


def instance_server_id():
    return 1234
