# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_collection_metrics():
    return False


def instance_enable_database_metrics():
    return False


def instance_enable_gc_metrics():
    return False


def instance_enable_index_metrics():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_min_collection_interval():
    return 15
