# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_cluster_name():
    return 'clickhouse'


def instance_collect_query_logs():
    return True


def instance_collect_text_logs():
    return True


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_exclude_internal_users():
    return True


def instance_initial_backfill_minutes():
    return 60


def instance_log_batch_size():
    return 1000


def instance_min_collection_interval():
    return 15


def instance_query_timeout_seconds():
    return 30


def instance_slow_query_threshold_ms():
    return 5000
