# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>


def instance_cd_port():
    return 1363


def instance_cd_protocol():
    return 'TCPIP'


def instance_disable_generic_tags():
    return False


def instance_empty_default_hostname():
    return False


def instance_enable_legacy_tags_normalization():
    return True


def instance_min_collection_interval():
    return 60


def instance_statistics_lookback_minutes():
    return 2


def instance_timeout():
    return 10


def instance_tls_verify():
    return True
