METRICS = {
    "Number of processed numeric (float) values per second": "processed.floats_per_sec",
    "Number of processed values per second": "processed.per_sec",
    "Number of processed character values per second": "processed.characters_per_sec",
    "Number of processed log values per second": "processed.logs_per_sec",
    "Number of processed numeric (unsigned) values per second": "processed.unsigned_per_sec",
    "Number of processed text values per second": "processed.text_per_sec",
    "Number of processed not supported values per second": "processed.unsupported_per_sec",
    "Utilization of alerter internal processes, in %": "process.internal.alerter",
    "Utilization of configuration syncer internal processes, in %": "process.internal.config_sync",
    "Utilization of escalator internal processes, in %": "process.internal.escalator",
    "Utilization of history syncer internal processes, in %": "process.internal.history_sync",
    "Utilization of housekeeper internal processes, in %": "process.internal.housekeeper",
    "Utilization of discoverer data collector processes, in %": "process.data_collector.discoverer",
    "Utilization of http poller data collector processes, in %": "process.data_collector.http_poller",
    "Utilization of icmp pinger data collector processes, in %": "process.data_collector.icmp_pinger",
    "Utilization of ipmi poller data collector processes, in %": "process.data_collector.ipmi_poller",
    "Utilization of java poller data collector processes, in %": "process.data_collector.java_poller",
    "Utilization of poller data collector processes, in %": "process.data_collector.poller",
    "Utilization of proxy poller data collector processes, in %": "process.data_collector.proxy_poller",
    "Utilization of self-monitoring internal processes, in %": "process.internal.self_monitoring",
    "Utilization of snmp trapper data collector processes, in %": "process.data_collector.snmp_trapper",
    "Utilization of timer internal processes, in %": "process.internal.timer",
    "Utilization of trapper data collector processes, in %": "process.data_collector.trapper",
    "Utilization of unreachable poller data collector processes, in %": "process.data_collector.unreachable_poller",
    "Zabbix queue over 10 minutes": "queue.duration_10",
    "Zabbix queue": "queue.size",
    "Zabbix configuration cache, % used": "cache.config",
    "Zabbix history write cache, % used": "cache.write",
    "Zabbix history index cache, % used": "cache.index",
    "Zabbix trend write cache, % used": "cache.write_trend",
    "Zabbix agent ping": "agent.ping",
    "Utilization of vmware data collector processes, in %": "process.data_collector.vmware",
    "Zabbix value cache, % used": "cache.value",
    "Zabbix value cache hits": "cache.value.hits",
    "Zabbix value cache misses": "cache.value.misses",
    "Zabbix vmware cache, % used": "cache.vmware",
    "Zabbix value cache operating mode": "cache.operating_mode",
    "Utilization of task manager internal processes, in %": "process.internal.task_manager",
    "Utilization of ipmi manager internal processes, in %": "process.internal.ipmi_manager",
    "Utilization of alert manager internal processes, in %": "process.internal.alert_manager",
    "Utilization of preprocessing manager internal processes, in %": "process.internal.preprocessing_manager",
    "Utilization of preprocessing worker internal processes, in %": "process.internal.preprocessing_worker",
    "Zabbix preprocessing queue": "queue.preprocessing",
    "Zabbix LLD queue": "queue.lld",
    "Utilization of LLD manager internal processes, in %": "process.internal.lld_manager",
    "Utilization of LLD worker internal processes, in %": "process.internal.lld_worker",
    "Number of CPUs": "cpu.count",
    "CPU iowait time": "cpu.iowait_time",
    "Context switches per second": "context_switches_per_sec",
    "CPU guest nice time": "cpu.guest_nice_time",
    "CPU guest time": "cpu.guest_time",
    "CPU softirq time": "cpu.softirq_time",
    "CPU interrupt time": "cpu.interrupt_time",
    "CPU steal time": "cpu.steal_time",
    "CPU nice time": "cpu.nice_time",
    "Load average (1m avg)": "load.avg.1_min",
    "CPU user time": "cpu.user_time",
    "CPU system time": "cpu.system_time",
    "CPU idle time": "cpu.idle_time",
    "Load average (15m avg)": "load.avg.15_min",
    "Load average (5m avg)": "load.avg.5_min",
    "Interrupts per second": "interrupts_per_sec",
    "Available memory in %": "memory.avail_percent",
    "Total memory": "memory.total",
    "Available memory": "memory.avail",
    "Total swap space": "swap_space.total",
    "Free swap space": "swap_space.free",
    "Free swap space in %": "swap_space.free_percent",
    "System uptime": "system.uptime",
    "System boot time": "system.boot_time",
    "System local time": "system.local_time",
    "Number of logged in users": "user.logged_in",
    "Maximum number of open file descriptors": "open_fd.max",
    "Maximum number of processes": "processes_max",
    "Number of processes": "processes_count",
    "Number of running processes": "processes_running_count",
    "CPU utilization": "cpu.used",
    "Zabbix agent availability": "agent.avail",
    "Utilization of alert syncer internal processes, in %": "process.internal.alert_sync",
    "Memory utilization": "memory.used",
}
