name: Redis Enterprise Prometheus
files:
- name: redis_enterprise_prometheus.yaml
  options:
  - template: init_config
    options:
    - template: init_config/default
  - template: instances
    options:
    - template: instances/openmetrics
