# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_alerts_limit(field, value):
    return get_default_field_value(field, value)


def instance_organization_id(field, value):
    return get_default_field_value(field, value)


def instance_threat_level(field, value):
    return get_default_field_value(field, value)


def instance_threat_type(field, value):
    return get_default_field_value(field, value)
