counter = {
    'grafana_alerting_remote_alertmanager_configuration_sync_failures': (
        'alerting_remote_alertmanager_configuration_sync_failures'
    ),
    'grafana_alerting_state_history_writes_bytes': 'alerting_state_history_writes_bytes',
    'grafana_encryption_cache_reads': 'encryption_cache_reads',
    'grafana_registered_metrics': 'registered_metrics',
    'grafana_authn_authn_failed_authentication': 'authn_authn_failed_authentication',
    'grafana_alerting_alerts_invalid': 'alerting_alerts_invalid',
    'grafana_apiserver_storage_data_key_generation_failures': 'apiserver_storage_data_key_generation_failures',
    'grafana_api_user_signup_invite': 'api_user_signup_invite',
    'grafana_alerting_nflog_gossip_messages_propagated': 'alerting_nflog_gossip_messages_propagated',
    'grafana_database_conn_max_idle_closed_seconds': 'database_conn_max_idle_closed_seconds',
    'grafana_database_conn_wait_duration_seconds': 'database_conn_wait_duration_seconds',
    'grafana_apiserver_audit_requests_rejected': 'apiserver_audit_requests_rejected',
    'grafana_database_conn_max_idle_closed': 'database_conn_max_idle_closed',
    'grafana_api_models_dashboard_insert': 'api_models_dashboard_insert',
    'grafana_access_evaluation_count': 'access_evaluation_count',
    'grafana_database_conn_wait_count': 'database_conn_wait_count',
    'grafana_live_node_messages_received_count': 'live_node_messages_received_count',
    'grafana_api_admin_user_created': 'api_admin_user_created',
    'grafana_api_user_signup_started': 'api_user_signup_started',
    'grafana_api_org_create': 'api_org_create',
    'grafana_alerting_nflog_queries': 'alerting_nflog_queries',
    'grafana_process_network_receive_bytes': 'process_network_receive_bytes',
    'grafana_alerting_silences_gossip_messages_propagated': 'alerting_silences_gossip_messages_propagated',
    'grafana_api_login_oauth': 'api_login_oauth',
    'grafana_encryption_ops': 'encryption_ops',
    'grafana_apiserver_kube_aggregator_x509_insecure_sha1': 'apiserver_kube_aggregator_x509_insecure_sha1',
    'grafana_api_dashboard_snapshot_external': 'api_dashboard_snapshot_external',
    'grafana_live_broker_redis_pub_sub_dropped_messages': 'live_broker_redis_pub_sub_dropped_messages',
    'grafana_api_dashboard_snapshot_get': 'api_dashboard_snapshot_get',
    'grafana_api_user_signup_completed': 'api_user_signup_completed',
    'grafana_cardinality_enforcement_unexpected_categorizations': 'cardinality_enforcement_unexpected_categorizations',
    'grafana_api_login_saml': 'api_login_saml',
    'grafana_alerting_remote_alertmanager_configuration_syncs': 'alerting_remote_alertmanager_configuration_syncs',
    'grafana_folder_id_api_count': 'folder_id_api_count',
    'grafana_page_response_status': 'page_response_status',
    'grafana_idforwarding_idforwarding_token_signing': 'idforwarding_idforwarding_token_signing',
    'grafana_process_cpu_seconds': 'process_cpu_seconds',
    'grafana_database_conn_max_lifetime_closed': 'database_conn_max_lifetime_closed',
    'grafana_hidden_metrics': 'hidden_metrics',
    'grafana_idforwarding_idforwarding_token_signing_from_cache': 'idforwarding_idforwarding_token_signing_from_cache',
    'grafana_api_login_post': 'api_login_post',
    'grafana_alerting_alerts_received': 'alerting_alerts_received',
    'grafana_alerting_silences_query_errors': 'alerting_silences_query_errors',
    'grafana_aggregator_discovery_aggregation_count': 'aggregator_discovery_aggregation_count',
    'grafana_alerting_silences_queries': 'alerting_silences_queries',
    'grafana_api_response_status': 'api_response_status',
    'grafana_apiserver_webhooks_x509_insecure_sha1': 'apiserver_webhooks_x509_insecure_sha1',
    'grafana_emails_sent_failed': 'emails_sent_failed',
    'grafana_apiserver_tls_handshake_errors': 'apiserver_tls_handshake_errors',
    'grafana_public_dashboard_request_count': 'public_dashboard_request_count',
    'grafana_proxy_response_status': 'proxy_response_status',
    'grafana_database_migrations': 'database_migrations',
    'grafana_folder_id_service_count': 'folder_id_service_count',
    'grafana_instance_start': 'instance_start',
    'grafana_alerting_nflog_query_errors': 'alerting_nflog_query_errors',
    'grafana_disabled_metrics': 'disabled_metrics',
    'grafana_alerting_remote_alertmanager_state_syncs': 'alerting_remote_alertmanager_state_syncs',
    'grafana_access_search_user_permissions_cache_usage': 'access_search_user_permissions_cache_usage',
    'grafana_apiserver_storage_envelope_transformation_cache_misses': (
        'apiserver_storage_envelope_transformation_cache_misses'
    ),
    'grafana_apiserver_webhooks_x509_missing_san': 'apiserver_webhooks_x509_missing_san',
    'grafana_access_permissions_cache_usage': 'access_permissions_cache_usage',
    'grafana_live_node_messages_sent_count': 'live_node_messages_sent_count',
    'grafana_db_datasource_query_by_id': 'db_datasource_query_by_id',
    'grafana_api_dashboard_snapshot_create': 'api_dashboard_snapshot_create',
    'grafana_plugins_preinstall': 'plugins_preinstall',
    'grafana_apiserver_audit_event': 'apiserver_audit_event',
    'grafana_idforwarding_idforwarding_failed_token_signing': 'idforwarding_idforwarding_failed_token_signing',
    'grafana_alerting_remote_alertmanager_state_sync_failures': 'alerting_remote_alertmanager_state_sync_failures',
    'grafana_process_network_transmit_bytes': 'process_network_transmit_bytes',
    'grafana_apiserver_kube_aggregator_x509_missing_san': 'apiserver_kube_aggregator_x509_missing_san',
    'grafana_emails_sent': 'emails_sent',
}
gauge = {
    'grafana_process_resident_memory_bytes': 'process_resident_memory_bytes',
    'grafana_database_conn_in_use': 'database_conn_in_use',
    'grafana_alerting_scheduler_behind_seconds': 'alerting_scheduler_behind_seconds',
    'grafana_index_server_index_size': 'index_server_index_size',
    'grafana_stat_totals_annotations': 'stat_totals_annotations',
    'grafana_stat_totals_library_variables': 'stat_totals_library_variables',
    'grafana_stat_active_users': 'stat_active_users',
    'grafana_apiserver_envelope_encryption_dek_cache_fill_percent': (
        'apiserver_envelope_encryption_dek_cache_fill_percent'
    ),
    'grafana_process_virtual_memory_max_bytes': 'process_virtual_memory_max_bytes',
    'grafana_alerting_alertmanager_config_match': 'alerting_alertmanager_config_match',
    'grafana_alerting_remote_alertmanager_last_readiness_check_timestamp_seconds': (
        'alerting_remote_alertmanager_last_readiness_check_timestamp_seconds'
    ),
    'grafana_stat_total_playlists': 'stat_total_playlists',
    'grafana_live_node_num_subscriptions': 'live_node_num_subscriptions',
    'grafana_apiserver_flowcontrol_seat_fair_frac': 'apiserver_flowcontrol_seat_fair_frac',
    'grafana_process_open_fds': 'process_open_fds',
    'grafana_alerting_dispatcher_aggregation_groups': 'alerting_dispatcher_aggregation_groups',
    'grafana_database_conn_max_open': 'database_conn_max_open',
    'grafana_build_info': 'build_info',
    'grafana_live_node_num_clients': 'live_node_num_clients',
    'grafana_stat_total_migrated_api_keys_to_sa_tokens': 'stat_total_migrated_api_keys_to_sa_tokens',
    'grafana_rendering_queue_size': 'rendering_queue_size',
    'grafana_stat_totals_dashboard_versions': 'stat_totals_dashboard_versions',
    'grafana_alerting_alertmanager_config_object_matchers': 'alerting_alertmanager_config_object_matchers',
    'grafana_alerting_alertmanager_config_matchers': 'alerting_alertmanager_config_matchers',
    'grafana_stat_totals_viewers': 'stat_totals_viewers',
    'grafana_database_conn_open': 'database_conn_open',
    'grafana_alerting_silences_snapshot_size_bytes': 'alerting_silences_snapshot_size_bytes',
    'grafana_stat_totals_rule_groups': 'stat_totals_rule_groups',
    'grafana_stat_totals_active_editors': 'stat_totals_active_editors',
    'grafana_alerting_active_configurations': 'alerting_active_configurations',
    'grafana_alerting_state_history_info': 'alerting_state_history_info',
    'grafana_alerting_remote_alertmanager_last_configuration_sync_timestamp_seconds': (
        'alerting_remote_alertmanager_last_configuration_sync_timestamp_seconds'
    ),
    'grafana_stat_totals_folder': 'stat_totals_folder',
    'grafana_stat_totals_data_keys': 'stat_totals_data_keys',
    'grafana_database_conn_idle': 'database_conn_idle',
    'grafana_alerting_discovered_configurations': 'alerting_discovered_configurations',
    'grafana_process_start_time_seconds': 'process_start_time_seconds',
    'grafana_alerting_remote_alertmanager_last_state_sync_timestamp_seconds': (
        'alerting_remote_alertmanager_last_state_sync_timestamp_seconds'
    ),
    'grafana_stat_totals_dashboard': 'stat_totals_dashboard',
    'grafana_plugin_build_info': 'plugin_build_info',
    'grafana_stat_total_teams': 'stat_total_teams',
    'grafana_alerting_alertmanager_config_size_bytes': 'alerting_alertmanager_config_size_bytes',
    'grafana_live_node_num_users': 'live_node_num_users',
    'grafana_apiserver_current_inflight_requests': 'apiserver_current_inflight_requests',
    'grafana_alerting_ticker_interval_seconds': 'alerting_ticker_interval_seconds',
    'grafana_alerting_alertmanager_inhibition_rules': 'alerting_alertmanager_inhibition_rules',
    'grafana_live_node_build': 'live_node_build',
    'grafana_stat_failed_migrated_api_keys_to_sa_tokens': 'stat_failed_migrated_api_keys_to_sa_tokens',
    'grafana_live_node_num_channels': 'live_node_num_channels',
    'grafana_alerting_ticker_last_consumed_tick_timestamp_seconds': (
        'alerting_ticker_last_consumed_tick_timestamp_seconds'
    ),
    'grafana_alerting_nflog_snapshot_size_bytes': 'alerting_nflog_snapshot_size_bytes',
    'grafana_plugin_target_info': 'plugin_target_info',
    'grafana_process_max_fds': 'process_max_fds',
    'grafana_stat_total_service_account_tokens': 'stat_total_service_account_tokens',
    'grafana_alerting_silences': 'alerting_silences',
    'grafana_stat_total_service_accounts_role_none': 'stat_total_service_accounts_role_none',
    'grafana_stat_totals_alert_rules': 'stat_totals_alert_rules',
    'grafana_stat_totals_correlations': 'stat_totals_correlations',
    'grafana_environment_info': 'environment_info',
    'grafana_alerting_alertmanager_config_match_re': 'alerting_alertmanager_config_match_re',
    'grafana_alerting_alertmanager_receivers': 'alerting_alertmanager_receivers',
    'grafana_stat_total_service_accounts': 'stat_total_service_accounts',
    'grafana_alerting_alertmanager_config_hash': 'alerting_alertmanager_config_hash',
    'grafana_stat_successfully_migrated_api_keys_to_sa_tokens': 'stat_successfully_migrated_api_keys_to_sa_tokens',
    'grafana_alerting_ticker_next_tick_timestamp_seconds': 'alerting_ticker_next_tick_timestamp_seconds',
    'grafana_apiserver_storage_objects': 'apiserver_storage_objects',
    'grafana_stat_totals_active_admins': 'stat_totals_active_admins',
    'grafana_alerting_schedule_alert_rules': 'alerting_schedule_alert_rules',
    'grafana_alerting_alertmanager_integrations': 'alerting_alertmanager_integrations',
    'grafana_alerting_alerts': 'alerting_alerts',
    'grafana_stat_totals_active_viewers': 'stat_totals_active_viewers',
    'grafana_feature_toggles_info': 'feature_toggles_info',
    'grafana_live_node_num_nodes': 'live_node_num_nodes',
    'grafana_alerting_alertmanager_alerts': 'alerting_alertmanager_alerts',
    'grafana_http_request_in_flight': 'http_request_in_flight',
    'grafana_process_virtual_memory_bytes': 'process_virtual_memory_bytes',
    'grafana_stat_total_users': 'stat_total_users',
    'grafana_alerting_active_alerts': 'alerting_active_alerts',
    'grafana_stat_totals_admins': 'stat_totals_admins',
    'grafana_alerting_schedule_alert_rules_hash': 'alerting_schedule_alert_rules_hash',
    'grafana_stat_totals_public_dashboard': 'stat_totals_public_dashboard',
    'grafana_stat_totals_editors': 'stat_totals_editors',
    'grafana_stat_total_orgs': 'stat_total_orgs',
    'grafana_stat_totals_library_panels': 'stat_totals_library_panels',
    'grafana_build_timestamp': 'build_timestamp',
}
histogram = {
    'grafana_alerting_state_full_sync_duration_seconds': 'alerting_state_full_sync_duration_seconds',
    'grafana_plugins_preinstall_duration_seconds': 'plugins_preinstall_duration_seconds',
    'grafana_frontend_boot_first_paint_time_seconds': 'frontend_boot_first_paint_time_seconds',
    'grafana_frontend_boot_load_time_seconds': 'frontend_boot_load_time_seconds',
    'grafana_search_dashboard_search_successes_duration_seconds': 'search_dashboard_search_successes_duration_seconds',
    'grafana_access_search_permissions_duration': 'access_search_permissions_duration',
    'grafana_database_migration_duration_seconds': 'database_migration_duration_seconds',
    'grafana_search_dashboard_search_failures_duration_seconds': 'search_dashboard_search_failures_duration_seconds',
    'grafana_frontend_boot_js_done_time_seconds': 'frontend_boot_js_done_time_seconds',
    'grafana_http_request_duration_seconds': 'http_request_duration_seconds',
    'grafana_frontend_plugins_preload_ms': 'frontend_plugins_preload_ms',
    'grafana_alerting_schedule_periodic_duration_seconds': 'alerting_schedule_periodic_duration_seconds',
    'grafana_apiserver_storage_data_key_generation_duration_seconds': (
        'apiserver_storage_data_key_generation_duration_seconds'
    ),
    'grafana_access_evaluation_duration': 'access_evaluation_duration',
    'grafana_live_node_pub_sub_lag_seconds': 'live_node_pub_sub_lag_seconds',
    'grafana_access_permissions_duration': 'access_permissions_duration',
    'grafana_database_all_migrations_duration_seconds': 'database_all_migrations_duration_seconds',
    'grafana_alerting_nflog_query_duration_seconds': 'alerting_nflog_query_duration_seconds',
    'grafana_alerting_silences_query_duration_seconds': 'alerting_silences_query_duration_seconds',
    'grafana_alerting_schedule_query_alert_rules_duration_seconds': (
        'alerting_schedule_query_alert_rules_duration_seconds'
    ),
    'grafana_alerting_notification_latency_seconds': 'alerting_notification_latency_seconds',
    'grafana_idforwarding_idforwarding_token_signing_duration_seconds': (
        'idforwarding_idforwarding_token_signing_duration_seconds'
    ),
    'grafana_apiserver_client_certificate_expiration_seconds': 'apiserver_client_certificate_expiration_seconds',
    'grafana_alerting_state_calculation_duration_seconds': 'alerting_state_calculation_duration_seconds',
    'grafana_frontend_boot_first_contentful_paint_time_seconds': 'frontend_boot_first_contentful_paint_time_seconds',
    'grafana_frontend_boot_css_time_seconds': 'frontend_boot_css_time_seconds',
    'grafana_storage_server_poller_query_latency_seconds': 'storage_server_poller_query_latency_seconds',
}
summary = {
    'grafana_api_dashboard_search_milliseconds': 'api_dashboard_search_milliseconds',
    'grafana_alerting_nflog_snapshot_duration_seconds': 'alerting_nflog_snapshot_duration_seconds',
    'grafana_alerting_execution_time_milliseconds': 'alerting_execution_time_milliseconds',
    'grafana_alerting_dispatcher_alert_processing_duration_seconds': (
        'alerting_dispatcher_alert_processing_duration_seconds'
    ),
    'grafana_api_dashboard_get_milliseconds': 'api_dashboard_get_milliseconds',
    'grafana_ldap_users_sync_execution_time': 'ldap_users_sync_execution_time',
    'grafana_api_dashboard_save_milliseconds': 'api_dashboard_save_milliseconds',
    'grafana_alerting_silences_snapshot_duration_seconds': 'alerting_silences_snapshot_duration_seconds',
    'grafana_api_dataproxy_request_all_milliseconds': 'api_dataproxy_request_all_milliseconds',
    'grafana_alerting_silences_gc_duration_seconds': 'alerting_silences_gc_duration_seconds',
    'grafana_live_client_command_duration_seconds': 'live_client_command_duration_seconds',
    'grafana_alerting_nflog_gc_duration_seconds': 'alerting_nflog_gc_duration_seconds',
}
METRIC_MAP = {**counter, **gauge, **histogram, **summary}
