import json


def read_file(file_path, is_json=False):
    with open(file_path, "r") as f:
        return json.load(f) if is_json else f.read()


OM_METRICS = [
    "qdrant.app.status.recovery.mode",
    "qdrant.collections.total",
    "qdrant.collections.vector.total",
    "qdrant.collection.vectors",
    "qdrant.collection.active.replicas.min",
    "qdrant.collection.active.replicas.max",
    "qdrant.collection.running.optimizations",
    "qdrant.collection.points",
    "qdrant.collection.dead.replicas",
    "qdrant.snapshot.creation.running",
    "qdrant.snapshot.recovery.running",
    "qdrant.snapshot.created.count",
    "qdrant.rest.responses.avg.duration.seconds",
    "qdrant.rest.responses.min.duration.seconds",
    "qdrant.rest.responses.max.duration.seconds",
    "qdrant.rest.responses.duration.seconds.count",
    "qdrant.rest.responses.duration.seconds.sum",
    "qdrant.rest.responses.duration.seconds.bucket",
    "qdrant.cluster.enabled",
    "qdrant.cluster.peers.total",
    "qdrant.cluster.term.count",
    "qdrant.cluster.commit.count",
    "qdrant.cluster.pending.operations.total",
    "qdrant.cluster.voter",
    "qdrant.rest.responses.count",
    "qdrant.rest.responses.fail.count",
    "qdrant.collection.hardware.metric.cpu.count",
    "qdrant.collection.hardware.metric.payload.io.read.count",
    "qdrant.collection.hardware.metric.payload.index.io.read.count",
    "qdrant.collection.hardware.metric.payload.index.io.write.count",
    "qdrant.collection.hardware.metric.payload.io.write.count",
    "qdrant.collection.hardware.metric.vector.io.read.count",
    "qdrant.collection.hardware.metric.vector.io.write.count",
    "qdrant.memory.active.bytes",
    "qdrant.memory.metadata.bytes",
    "qdrant.memory.resident.bytes",
    "qdrant.memory.retained.bytes",
    "qdrant.memory.allocated.bytes",
    "qdrant.process.threads",
    "qdrant.process.open.mmaps",
    "qdrant.system.max.mmaps",
    "qdrant.process.open.fds",
    "qdrant.process.max.fds",
    "qdrant.process.minor.page.faults.count",
    "qdrant.process.major.page.faults.count",
]
