# All ScaleOps metrics are exposed as gauges through the Prometheus federation endpoint,
# which does not include metric type declarations.
METRIC_MAP = {
    'scaleops_health_check': {'name': 'health_check', 'type': 'gauge'},
    'scaleops_events': {'name': 'events', 'type': 'gauge'},
    'scaleops_alerts': {'name': 'alerts', 'type': 'gauge'},
    'scaleops_multi_cluster_child_connection_status': {
        'name': 'multi_cluster_child_connection_status',
        'type': 'gauge',
    },
    'scaleops_recommendation_managed_workload_status': {
        'name': 'recommendation_managed_workload_status',
        'type': 'gauge',
    },
    'scaleops_total_automated_workloads': {'name': 'total_automated_workloads', 'type': 'gauge'},
    'scaleops_cluster_automation_score': {'name': 'cluster_automation_score', 'type': 'gauge'},
    'scaleops_sum_workloads_oom': {'name': 'sum_workloads_oom', 'type': 'gauge'},
    'scaleops_namespace_auto_state': {'name': 'namespace_auto_state', 'type': 'gauge'},
    'scaleops_estimated_monthly_costs': {'name': 'estimated_monthly_costs', 'type': 'gauge'},
    'scaleops_hpa_optimization_gap': {'name': 'hpa_optimization_gap', 'type': 'gauge'},
    'scaleops_underprovisioned_workloads': {'name': 'underprovisioned_workloads', 'type': 'gauge'},
    'scaleops_sum_automated_pods_count': {'name': 'sum_automated_pods_count', 'type': 'gauge'},
    'scaleops_recommendation_attached_policy': {'name': 'recommendation_attached_policy', 'type': 'gauge'},
    'scaleops_zdt_pod_force_delete': {'name': 'zdt_pod_force_delete', 'type': 'gauge'},
    'scaleops_updater_failed_evictions': {'name': 'updater_failed_evictions', 'type': 'gauge'},
    'scaleops_total_unautomated_workloads': {'name': 'total_unautomated_workloads', 'type': 'gauge'},
    'scaleops_argo_out_of_sync_object': {'name': 'argo_out_of_sync_object', 'type': 'gauge'},
    'scaleops_health_check_admissions': {'name': 'health_check_admissions', 'type': 'gauge'},
    'scaleops_dashboard_wasted_resources': {'name': 'dashboard_wasted_resources', 'type': 'gauge'},
    'scaleops_nodes_total_hourly_cost': {'name': 'nodes_total_hourly_cost', 'type': 'gauge'},
    'scaleops_total_workloads_by_type': {'name': 'total_workloads_by_type', 'type': 'gauge'},
    'scaleops_prometheus_tsdb_storage_usage_percentage': {
        'name': 'prometheus_tsdb_storage_usage_percentage',
        'type': 'gauge',
    },
    'scaleops_min_replicas_active_savings': {'name': 'min_replicas_active_savings', 'type': 'gauge'},
    'scaleops_evictions_by_types_count': {'name': 'evictions_by_types_count', 'type': 'gauge'},
    'scaleops_consolidation_system_errors': {'name': 'consolidation_system_errors', 'type': 'gauge'},
    'scaleops_min_replicas_available_savings': {'name': 'min_replicas_available_savings', 'type': 'gauge'},
    'scaleops_automated_not_optimized_workloads': {'name': 'automated_not_optimized_workloads', 'type': 'gauge'},
    'scaleops_kubelet_eviction_event_count': {'name': 'kubelet_eviction_event_count', 'type': 'gauge'},
    'scaleops_workload_recommendation_not_updated': {'name': 'workload_recommendation_not_updated', 'type': 'gauge'},
    'scaleops_pod_container_resource_recommendation_requests': {
        'name': 'pod_container_resource_recommendation_requests',
        'type': 'gauge',
    },
    'scaleops_hpa_threshold_optimization_gap': {'name': 'hpa_threshold_optimization_gap', 'type': 'gauge'},
    'scaleops_avg_active_node_monthly_cost': {'name': 'avg_active_node_monthly_cost', 'type': 'gauge'},
    'scaleops_memory_underprovisioned_pods_on_stress_nodes': {
        'name': 'memory_underprovisioned_pods_on_stress_nodes',
        'type': 'gauge',
    },
    'scaleops_total_argo_out_of_sync_hpa_objects_count': {
        'name': 'total_argo_out_of_sync_hpa_objects_count',
        'type': 'gauge',
    },
    'scaleops_workloads_with_cpu_throttle_percentage_higher_than_75_count': {
        'name': 'workloads_with_cpu_throttle_percentage_higher_than_75_count',
        'type': 'gauge',
    },
}
