METRIC_MAP = {
    ## Resilience4j Metrics
    "resilience4j_bulkhead_available_concurrent_calls": "bulkhead.available.concurrent.calls",
    "resilience4j_bulkhead_max_allowed_concurrent_calls": "bulkhead.max.allowed.concurrent.calls",
    "resilience4j_bulkhead_max_thread_pool_size": "bulkhead.max.thread.pool.size",
    "resilience4j_bulkhead_queue_capacity": "bulkhead.queue.capacity",
    "resilience4j_bulkhead_queue_depth": "bulkhead.queue.depth",
    "resilience4j_bulkhead_thread_pool_size": "bulkhead.thread.pool.size",
    "resilience4j_circuitbreaker_buffered_calls": "circuitbreaker.buffered.calls",
    "resilience4j_circuitbreaker_calls_seconds_count": "circuitbreaker.calls.seconds.count",
    "resilience4j_circuitbreaker_calls_seconds_max": "circuitbreaker.calls.seconds.max",
    "resilience4j_circuitbreaker_calls_seconds_sum": "circuitbreaker.calls.seconds.sum",
    "resilience4j_circuitbreaker_calls_seconds": "circuitbreaker.calls.seconds",
    "resilience4j_circuitbreaker_calls_total": "circuitbreaker.calls",
    "resilience4j_circuitbreaker_failure_rate": "circuitbreaker.failure.rate",
    "resilience4j_circuitbreaker_max_buffered_calls": "circuitbreaker.max.buffered.calls",
    "resilience4j_circuitbreaker_state": "circuitbreaker.state",
    "resilience4j_ratelimiter_available_permissions": "ratelimiter.available.permissions",
    "resilience4j_ratelimiter_waiting_threads": "ratelimiter.waiting.threads",
    "resilience4j_retry_calls": "retry.calls",
    "resilience4j_timelimiter_calls_total": "timelimiter.calls",
}
