trigger: none

pr:
  branches:
    include:
    - master

variables:
  DDEV_COLOR: 1
  DD_TRACE_AGENT_PORT: 8127

resources:
  repositories:
    - repository: integrations-core
      type: github
      name: Datadog/integrations-core
      ref: master
      endpoint: DataDog
  containers:
    - ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      - container: dd_agent
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8127:8126
        env:
          DD_API_KEY: $(DD_CI_API_KEY)
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"

jobs:
- template: '.azure-pipelines/templates/test-single-linux.yml@integrations-core'
  parameters:
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      ddtrace_flag: '--ddtrace'
    job_name: Changed
    display: Linux
    validate: false
    validate_changed: changed
    validate_codeowners: true
    repo: 'extras'

- template: '.azure-pipelines/templates/test-single-windows.yml@integrations-core'
  parameters:
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      ddtrace_flag: '--ddtrace'
    job_name: Changed
    check: '--changed none_yet'
    validate_changed: changed
    display: Windows
    repo: 'extras'
