name: PR

on:
  pull_request:
    branches:
    - master
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: DataDog/integrations-core/.github/workflows/pr-test.yml@c9d96c04c9603581becabc1a122159d42878abfa # master
    with:
      repo: extras
      python-version: "3.13"
    secrets: inherit
    permissions:
       # needed for compute-matrix in test-target.yml
       contents: read
