# (C) Calastone Ltd. 2018
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

ALL_METRICS = {
    # Generic stats
    '/stats': [
        {"json_path": "proc.mem", "json_type": "int", "metric_name": "eventstore.proc.mem", "metric_type": "gauge"},
        {"json_path": "proc.cpu", "json_type": "float", "metric_name": "eventstore.proc.cpu", "metric_type": "gauge"},
        {
            "json_path": "proc.threadsCount",
            "json_type": "int",
            "metric_name": "eventstore.proc.threads",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.contentionsRate",
            "json_type": "float",
            "metric_name": "eventstore.proc.contentions_rate",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.thrownExceptionsRate",
            "json_type": "float",
            "metric_name": "eventstore.proc.thrown_exceptions_rate",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.diskIo.readBytes",
            "json_type": "int",
            "metric_name": "eventstore.proc.disk.read_bytes",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.diskIo.writtenBytes",
            "json_type": "int",
            "metric_name": "eventstore.proc.disk.write_bytes",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.diskIo.readOps",
            "json_type": "int",
            "metric_name": "eventstore.proc.disk.read_ops",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.diskIo.writeOps",
            "json_type": "int",
            "metric_name": "eventstore.proc.disk.write_ops",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.connections",
            "json_type": "int",
            "metric_name": "eventstore.tcp.connections",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.receivingSpeed",
            "json_type": "float",
            "metric_name": "eventstore.tcp.receiving_speed",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.sendingSpeed",
            "json_type": "float",
            "metric_name": "eventstore.tcp.sending_speed",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.inSend",
            "json_type": "int",
            "metric_name": "eventstore.tcp.in_send",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.measureTime",
            "json_type": "datetime",
            "metric_name": "eventstore.tcp.measure_time",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.pendingReceived",
            "json_type": "int",
            "metric_name": "eventstore.tcp.pending_received",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.pendingSend",
            "json_type": "int",
            "metric_name": "eventstore.tcp.pending_send",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.receivedBytesSinceLastRun",
            "json_type": "int",
            "metric_name": "eventstore.tcp.received_bytes.since_last_run",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.receivedBytesTotal",
            "json_type": "int",
            "metric_name": "eventstore.tcp.received_bytes.total",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.sentBytesSinceLastRun",
            "json_type": "int",
            "metric_name": "eventstore.tcp.sent_bytes.since_last_run",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.tcp.sentBytesTotal",
            "json_type": "int",
            "metric_name": "eventstore.tcp.sent_bytes.total",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.allocationSpeed",
            "json_type": "float",
            "metric_name": "eventstore.gc.allocation_speed",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen0ItemsCount",
            "json_type": "float",
            "metric_name": "eventstore.gc.items_count.gen0",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen0Size",
            "json_type": "float",
            "metric_name": "eventstore.gc.size.gen0",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen1ItemsCount",
            "json_type": "float",
            "metric_name": "eventstore.gc.items_count.gen1",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen1Size",
            "json_type": "float",
            "metric_name": "eventstore.gc.size.gen1",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen2ItemsCount",
            "json_type": "float",
            "metric_name": "eventstore.gc.items_count.gen2",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.gen2Size",
            "json_type": "float",
            "metric_name": "eventstore.gc.size.gen2",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.largeHeapSize",
            "json_type": "int",
            "metric_name": "eventstore.gc.large_heap_size",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.timeInGc",
            "json_type": "float",
            "metric_name": "eventstore.gc.time_in_gc",
            "metric_type": "gauge",
        },
        {
            "json_path": "proc.gc.totalBytesInHeaps",
            "json_type": "int",
            "metric_name": "eventstore.gc.total_bytes_in_heaps",
            "metric_type": "gauge",
        },
        {
            "json_path": "sys.freeMem",
            "json_type": "int",
            "metric_name": "eventstore.sys.free_mem",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.queue.*.avgItemsPerSecond",
            "json_type": "int",
            "metric_name": "eventstore.es.queue.avg_items_per_second",
            "metric_type": "histogram",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.avgProcessingTime",
            "json_type": "float",
            "metric_name": "eventstore.es.queue.avg_processing_time",
            "metric_type": "histogram",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.currentIdleTime",
            "json_type": "datetime",
            "metric_name": "eventstore.es.queue.current_idle_time",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.currentItemProcessingTime",
            "json_type": "datetime",
            "metric_name": "eventstore.es.queue.current_processing_time",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.idleTimePercent",
            "json_type": "float",
            "metric_name": "eventstore.es.queue.idle_time_percent",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.length",
            "json_type": "int",
            "metric_name": "eventstore.es.queue.length",
            "metric_type": "histogram",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.lengthCurrentTryPeak",
            "json_type": "int",
            "metric_name": "eventstore.es.queue.length_current_try_peak",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.lengthLifetimePeak",
            "json_type": "int",
            "metric_name": "eventstore.es.queue.length_lifetime_peak",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.queue.*.totalItemsProcessed",
            "json_type": "int",
            "metric_name": "eventstore.es.queue.total_items_processed",
            "metric_type": "gauge",
            "tag_by": ["es.queue.*.queueName", "es.queue.*.groupName"],
        },
        {
            "json_path": "es.writer.lastFlushSize",
            "json_type": "int",
            "metric_name": "eventstore.es.writer.flush_size.last",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.lastFlushDelayMs",
            "json_type": "float",
            "metric_name": "eventstore.es.writer.flush_delay_ms.last",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.meanFlushSize",
            "json_type": "int",
            "metric_name": "eventstore.es.writer.flush_size.mean",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.meanFlushDelayMs",
            "json_type": "float",
            "metric_name": "eventstore.es.writer.flush_delay_ms.mean",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.maxFlushSize",
            "json_type": "int",
            "metric_name": "eventstore.es.writer.flush_size.max",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.maxFlushDelayMs",
            "json_type": "float",
            "metric_name": "eventstore.es.writer.flush_delay_ms.max",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.writer.queuedFlushMessages",
            "json_type": "int",
            "metric_name": "eventstore.es.writer.queued_flush_messages",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.cachedRecord",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.cached_record",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.notCachedRecord",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.not_cached_record",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.cachedStreamInfo",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.cached_stream_info",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.notCachedStreamInfo",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.not_cached_stream_info",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.cachedTransInfo",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.cached_trans_info",
            "metric_type": "gauge",
        },
        {
            "json_path": "es.readIndex.notCachedTransInfo",
            "json_type": "int",
            "metric_name": "eventstore.es.read_index.not_cached_trans_info",
            "metric_type": "gauge",
        },
    ],
    # Node information
    "/info": [
        {
            "json_path": "state",
            "json_type": "str",
            "metric_name": "eventstore.is_leader",
            "metric_type": "gauge",
            "match": "leader",
        },
        {
            "json_path": "state",
            "json_type": "str",
            "metric_name": "eventstore.is_follower",
            "metric_type": "gauge",
            "match": "follower",
        },
        {
            "json_path": "state",
            "json_type": "str",
            "metric_name": "eventstore.is_readonlyreplica",
            "metric_type": "gauge",
            "match": "readonlyreplica",
        },
    ],
    # Stats on projections
    '/projections/all-non-transient': [
        {
            "json_path": "projections.*.coreProcessingTime",
            "json_type": "int",
            "metric_name": "eventstore.projection.core_processing_time",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.version",
            "json_type": "int",
            "metric_name": "eventstore.projection.version",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.epoch",
            "json_type": "int",
            "metric_name": "eventstore.projection.epoch",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.readsInProgress",
            "json_type": "int",
            "metric_name": "eventstore.projection.reads_in_progress",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.writesInProgress",
            "json_type": "int",
            "metric_name": "eventstore.projection.writes_in_progress",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.partitionsCached",
            "json_type": "int",
            "metric_name": "eventstore.projection.partitions_cached",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.status",
            "json_type": "str",
            "metric_name": "eventstore.projection.running",
            "metric_type": "gauge",
            "match": "Running",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.progress",
            "json_type": "float",
            "metric_name": "eventstore.projection.progress",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.eventsProcessedAfterRestart",
            "json_type": "int",
            "metric_name": "eventstore.projection.events_processed_after_restart",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.bufferedEvents",
            "json_type": "int",
            "metric_name": "eventstore.projection.buffered_events",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.writePendingEventsBeforeCheckpoint",
            "json_type": "int",
            "metric_name": "eventstore.projection.write_pending_events_before_checkpoint",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
        {
            "json_path": "projections.*.writePendingEventsAfterCheckpoint",
            "json_type": "int",
            "metric_name": "eventstore.projection.write_pending_events_after_checkpoint",
            "metric_type": "gauge",
            "tag_by": ["projection:projections.*.effectiveName"],
        },
    ],
    # Stats on subscriptions
    '/subscriptions': [
        {
            "json_path": "*.status",
            "json_type": "str",
            "metric_name": "eventstore.subscription.live",
            "metric_type": "gauge",
            "match": "Live",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.averageItemsPerSecond",
            "json_type": "float",
            "metric_name": "eventstore.subscription.average_items_per_second",
            "metric_type": "histogram",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.totalItemsProcessed",
            "json_type": "int",
            "metric_name": "eventstore.subscription.items_processed",
            "metric_type": "gauge",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.lastProcessedEventNumber",
            "json_type": "int",
            "metric_name": "eventstore.subscription.last_processed_event_number",
            "metric_type": "gauge",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.lastKnownEventNumber",
            "json_type": "int",
            "metric_name": "eventstore.subscription.last_known_event_number",
            "metric_type": "gauge",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.connectionCount",
            "json_type": "int",
            "metric_name": "eventstore.subscription.connections",
            "metric_type": "gauge",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
        {
            "json_path": "*.totalInFlightMessages",
            "json_type": "int",
            "metric_name": "eventstore.subscription.messages_in_flight",
            "metric_type": "gauge",
            "tag_by": ["*.eventStreamId", "*.groupName"],
        },
    ],
    # Clustering stats
    '/gossip': [
        {
            "json_path": "members.*.isAlive",
            "json_type": "bool",
            "metric_name": "eventstore.cluster.member_alive",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.lastCommitPosition",
            "json_type": "int",
            "metric_name": "eventstore.cluster.last_commit_position",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.writerCheckpoint",
            "json_type": "int",
            "metric_name": "eventstore.cluster.writer_checkpoint",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.chaserCheckpoint",
            "json_type": "int",
            "metric_name": "eventstore.cluster.chaser_checkpoint",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.epochPosition",
            "json_type": "int",
            "metric_name": "eventstore.cluster.epoch_position",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.epochNumber",
            "json_type": "int",
            "metric_name": "eventstore.cluster.epoch_number",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
        {
            "json_path": "members.*.nodePriority",
            "json_type": "int",
            "metric_name": "eventstore.cluster.node_priority",
            "metric_type": "gauge",
            "tag_by": ["members.*.httpEndPointIp", "members.*.httpEndPointPort"],
        },
    ],
}
